added debug code and handled the worker disconnect case
J-Gravity/J-GravityDispatcher pull request #41
Opened 2017-05-19 04:03 UTC by coder-guy22296

2017-05-19 04:07 UTC, seanwessmith requested changes
we don't accept new connections in the launch_simulation.c function

2017-05-19 04:23 UTC, seanwessmith approved these changes

2017-05-19 04:23 UTC, seanwessmith commented on networking/Dispatcher/launch_simulation.c
> +		else if (msg.error == 0)
disconnect pthread[worker->tid]
free worker in linked list

2017-05-19 04:23 UTC, merged

2017-05-20 22:38 UTC, riking commented on networking/Dispatcher/launch_simulation.c
> +	sleep(999999);
you can sleep forever by locking a mutex twice

2017-05-21 20:56 UTC, seanwessmith commented on networking/Dispatcher/launch_simulation.c
> +	sleep(999999);
Thanks Kane, I'll replace the sleep with mutex